dependencies:
- name: demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: demo11
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: demo12
  repository: http://jenkins-x-chartmuseum:8080
  version: v0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
